spring:
  application:
    name: query-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/query

consumer:
  group-id: query-service
  topic:
    name: outbox_event.stock-updated

  properties:
    auto-offset-reset: earliest
    enable-auto-commit: false
    max-poll-records: 1

  concurrency: 3

  poll-timeout: 1000

  seek-to-current-error-handler:
    seek-after-rollback: true
    max-failure-attempts: 3

logging:
  level:
    org:
      hibernate: ERROR
      apache.kafka: ERROR
      springframework:
        orm.jpa: ERROR
        kafka: ERROR
        transaction: TRACE
        kafka.transaction: DEBUG

server:
  servlet:
    context-path: /api/v1